Projeto01.ConceitosMVC/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Projeto01.ConceitosMVC.Models
{
    public class Cliente
    {


        [Required(ErrorMessage = "Por favor, preencha o CPF.")] //Campo obrigatório
        [Display(Name = "CPF do Cliente")]
        [StringLength(11, MinimumLength = 11, ErrorMessage = "O CPF deve ter 11 dígitos.")] //Tamanho do campo
        public string Cpf { get; set; }

        [Required(ErrorMessage = "Por favor, preencha o nome.")] //Campo obrigatório
        [Display(Name = "Nome do Cliente")]
        public string Nome { get; set; }

        [Required(ErrorMessage = "Por favor, preencha a data de nascimento.")] //Campo obrigatório
        [Display(Name = "Data de Nascimento")]
        [DataType(DataType.Date)]
        public DateTime DataNascimento { get; set; }

        [Required()]
        [Display(Name = "UF Residência")]
        public string UfResidencia { get; set; }
    }
}

Projeto01.ConceitosMVC/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Projeto01.ConceitosMVC.Models
{
    //Modelo para a aplicação
    public class Produto
    {
        public int Codigo { get; set; }
        public string Descricao{ get; set; }
        public double Preco{ get; set; }

        
        public override string ToString()
        {
            return $"Código: {Codigo}, Descrição: {Descricao}, Preco: {Preco:c}";
        }
    }
}

Projeto01.ConceitosMVC/Controllers/ClientesController.cs
using Projeto01.ConceitosMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projeto01.ConceitosMVC.Controllers
{
    public class ClientesController : Controller
    {
        // GET: Clientes
        public ActionResult Index()
        {
            return View();
        }
        //Strongly typed views
        [HttpGet]
        public ActionResult Cadastro()
        {

            ViewBag.ListaEstados = new SelectList(new List<string>() { "RS", "PA", "SP", "RJ", "SC" });
            return View();
        }
        [HttpPost]
        public ActionResult Cadastro(Cliente cliente)
        {


            //temos que retornar o cadastro na verificação, se não, dará erro
            //verifica se os dados estão válidos, caso não, ele retorna o usuário para o formulário.
            if (!ModelState.IsValid)
            {
                return Cadastro();
            }
            //Não estamos direcionando para a View Exibir, nós só estamos mostrando o CONTEÚDO da View Exibir.
            return View("Exibir", cliente);
        }

        public ActionResult Exibir(Cliente cliente)
        {
            return View(cliente);
        }
        public ActionResult Listar01()
        {
            List<Cliente> clientes = new List<Cliente>()
            {
                new Cliente() {
                    Cpf = "12345678901", Nome = "Jose 1", DataNascimento = DateTime.Now, UfResidencia = "RJ" },
                new Cliente() {
                    Cpf = "78945612302", Nome = "Maria 1", DataNascimento = DateTime.Now, UfResidencia = "SC" },
                new Cliente() {
                    Cpf = "65474132598", Nome = "João 1", DataNascimento = DateTime.Now, UfResidencia = "SP" }
            };
            //Mostrar clientes da "view" Listar01 na view LISTAR
            return View("Listar", clientes);
        }

        public ActionResult Listar02()
        {
            HashSet<Cliente> clientes = new HashSet<Cliente>()
            {
                new Cliente() {
                    Cpf = "12345678901", Nome = "Jose 2", DataNascimento = DateTime.Now, UfResidencia = "RJ" },
                new Cliente() {
                    Cpf = "78945612302", Nome = "Maria 2", DataNascimento = DateTime.Now, UfResidencia = "SC" },
                new Cliente() {
                    Cpf = "65474132598", Nome = "João 2", DataNascimento = DateTime.Now, UfResidencia = "SP" }
            };
            //Mostrar clientes da "view" Listar02 na view LISTAR
            return View("Listar", clientes);
        }

    }
}

Projeto01.ConceitosMVC/Controllers/HomeController.cs
using Projeto01.ConceitosMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projeto01.ConceitosMVC.Controllers
{
    public class HomeController : Controller
    {
        public string MostrarTexto()
        {
            return "<h1>Conceitos do MVC</h1>";
        }

        public Produto MostrarProduto()
        {
            Produto produto = new Produto()
            {
                Codigo = 120,
                Descricao = "Armário",
                Preco = 1200.0
            };
            return produto;
        }
        public string MostrarValor(int id)
        {
            return $"Valor informado: {id}";
        }

        // GET: Home
        //Dentro do controle os métodos não são chamados de métodos, são chamados de Action 

        public ActionResult Index()
        {
            return View();
        }

    }
}

Projeto01.ConceitosMVC/Controllers/ProdutosController.cs
using Projeto01.ConceitosMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projeto01.ConceitosMVC.Controllers
{
    public class ProdutosController : Controller
    {
        // GET: Produtos

        public ActionResult Index()
        {
            return View();
        }
        //Por padrão todo action é executado pelo método get
        //Gera o formulário
        [HttpGet]
        public ActionResult Cadastro()
        {
            return View();
        }

        //Para receber os dados do form Cadastro.cshtml
        [HttpPost]
        public ActionResult Cadastro(FormCollection form)
        {
            //obtendo os dados do formulário
            int codigo = int.Parse(form["codigoTextBox"]);
            string descricao = form["descricaoTextBox"];
            double preco = double.Parse(form["precoTextBox"]);

            //criando um projeto da classe produto com os dados do formulário

            Produto produto = new Produto()
            {
                Codigo = codigo,
                Descricao = descricao,
                Preco = preco
            };
            return View("Exibir", produto);
        }
        //Esse action quando executado, ele irá gerar uma view, ele vai ter uma página e essa página vai receber o produto
        public ActionResult Exibir(Produto produto)
        {
            return View(produto);
        }
        [HttpGet]
        public ActionResult CadastroModel()
        {
            return View();
        }
        //Usando views fortementes tipadas - strongly typed views
        [HttpPost]
        public ActionResult CadastroModel(Produto produto)
        {
            return View("ExibirModel", produto);
        }
        public ActionResult ExibirModel(Produto produto)
        {
            return View(produto);
        }

    }
}

Projeto01.ConceitosMVC/Views/Clientes/Cadastro.cshtml
@model Projeto01.ConceitosMVC.Models.Cliente

@{
    ViewBag.Title = "Exibir";
}

<h2 class="titulo">Cadastro de Clientes</h2>


@using (Html.BeginForm())
{
    @*Expressão Lambda*@

<div class="input">
    @Html.LabelFor(m => m.Cpf)<br />
    @Html.EditorFor(m => m.Cpf)
    @Html.ValidationMessageFor(m => m.Cpf)
    <br />

    @Html.LabelFor(m => m.Nome)<br />
    @Html.EditorFor(m => m.Nome)
    @Html.ValidationMessageFor(m => m.Nome)
    <br />

    @Html.LabelFor(m => m.DataNascimento)<br />
    @Html.EditorFor(m => m.DataNascimento)
    @Html.ValidationMessageFor(m => m.DataNascimento)
    <br />

    @Html.LabelFor(m => m.UfResidencia)<br />
    @Html.DropDownListFor(m => m.UfResidencia, (SelectList)ViewBag.ListaEstados, "Escolha uma opção.", new { @style = "size: 40px" })
    @Html.ValidationMessageFor(m => m.UfResidencia)
    <br />
    <br />


    <input type="submit" value="Enviar" />
    <a>@Html.ActionLink("Voltar", "Index", "Clientes")</a>


</div>
}

Projeto01.ConceitosMVC/Views/Clientes/Exibir.cshtml
@model Projeto01.ConceitosMVC.Models.Cliente
@{
    ViewBag.Title = "Exibir clientes";
}

<h2>Dados do Clientes</h2>
<strong>CPF: </strong><span>@Model.Cpf</span>
<br />
<strong>Nome: </strong><span>@Model.Nome</span>
<br />
<strong>Data de Nascimento: </strong><span>@Model.DataNascimento.ToString("d")</span>
<br />
<strong>UF da Residência: </strong><span>@Model.UfResidencia</span>
<br />

Projeto01.ConceitosMVC/Views/Clientes/Index.cshtml
@{
    ViewBag.Title = "Clientes";
}

<h2 style="color: black">Clientes - Escolha uma opção</h2>

<ul>
    <li class="btn btn-primary">@Html.ActionLink("Cadastro de Clientes","Cadastro","Clientes")</li>
    <li class="btn btn-primary">@Html.ActionLink("Lista de Clientes (List)","Listar01","Clientes")</li>
    <li class="btn btn-primary">@Html.ActionLink("Lista de Clientes (HashSet)","Listar02","Clientes")</li>
</ul>

Projeto01.ConceitosMVC/Views/Clientes/Listar.cshtml
@model IEnumerable<Projeto01.ConceitosMVC.Models.Cliente>
@{
    ViewBag.Title = "Listar";
}
@* Layout da tabela *@
<center>
    <h2 class="titulo">Lista de Clientes</h2>
    <table border="1" class="table-responsive" id="tabela">
        <tr style="text-align: center; font-weight: bold">
            <td>CPF</td>
            <td>Nome</td>
            <td>Data de Nascimento</td>
            <td>UF</td>
        </tr>

        @foreach (var item in Model)
        {
            <tr style="text-align: center">
                <td>@item.Cpf</td>
                <td>@item.Nome</td>
                <td>@item.DataNascimento</td>
                <td>@item.UfResidencia</td>
            </tr>
        }
    </table>
</center>

<a>@Html.ActionLink("Voltar", "Index", "Clientes")</a>

Projeto01.ConceitosMVC/Views/Home/Index.cshtml
@{ 
    ViewBag.Title = "Início";

}    

<div style="text-align: center">
    <h1 class="texto" style="text-align: center; color: blaCK">Bem vindo(a)!</h1>
    <p style="color: black" class="glyphicon-envelope">Este é um projeto apenas para mostrar à vocês os conceitos básicos sobre MVC.</p>
  
</div>

Projeto01.ConceitosMVC/Views/Produtos/Cadastro.cshtml
@{
    ViewBag.Title = "Cadastro";
}

    <h2 class="titulo">Cadastro de Produtos</h2>
    @*Formulário*@
    <div>
        @*CRIANDO COM FORMULÁRIO *@
        @*TODO PARÂMETRO COMEÇADO COM "THIS" INDICA UM MÉTODO DE EXTENSÃO*@
        @*No BeginForm o método Post é padrão.*@
        @using (Html.BeginForm())
        {
            <span>Código:</span><br />
            @Html.TextBox("codigoTextBox")<br />

            <span>Descrição:</span><br />
            @Html.TextBox("descricaoTextBox")<br />

            <span>Preço:</span><br />
            @Html.TextBox("precoTextBox")<br />
            <br />

            <input type="submit" value="Enviar" />

        }
    </div>

Projeto01.ConceitosMVC/Views/Produtos/CadastroModel.cshtml
@model Projeto01.ConceitosMVC.Models.Produto

@{
    @* Titulo do site  *@
    ViewBag.Title = "Cadastro de Produtos";
}

<h2>Cadastro de Produtos</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Incluir Produto" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para o menu", "Index")
</div>

Projeto01.ConceitosMVC/Views/Produtos/Exibir.cshtml
@model Projeto01.ConceitosMVC.Models.Produto
@{
    ViewBag.Title = "Exibir";
}

<h2>Exibir Dados do Produto</h2>
<strong>Código: </strong><span>@Model.Codigo</span>
<br />
<strong>Descrição: </strong><span>@Model.Descricao</span>
<br />
<strong>Preço: </strong><span>@Model.Preco</span>
<br />

Projeto01.ConceitosMVC/Views/Produtos/ExibirModel.cshtml
@model Projeto01.ConceitosMVC.Models.Produto

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes do Produto</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @* DisplayNameFor funciona como label*@
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>

        <dd>
            @*`DisplayFor é o conteúdo *@
            @Html.DisplayFor(model => model.Codigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Preco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Preco)
        </dd>

    </dl>
</div>
<p> |
    @Html.ActionLink("Voltar para o menu", "Index")
</p>

Projeto01.ConceitosMVC/Views/Produtos/Index.cshtml
@{
    ViewBag.Title = "Produtos";
}

<h2>Produtos - Escolha uma opção</h2>

<ul>
    <li>@Html.ActionLink("Cadastro de Produtos", "Cadastro", "Produtos")</li>
    <li>@Html.ActionLink("Cadastro de Produtos (Model)", "CadastroModel", "Produtos")</li>
</ul>
    

Projeto01.ConceitosMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="corpo">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Conceitos MVC</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body class="corpo">
    <div class="navbar navbar-inverse navbar-fixed-top bg-custom-2" style="background-color: #91a6f6; height:55px!important">
        <div class="container">
            <div class="navbar-header" style="margin-left:-100px">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Conceitos MVC", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse texto">
                <ul class="nav navbar-nav">
                    <li class="texto">
                        @Html.ActionLink("Gestão de Clientes", "Index", "Clientes")
                    </li>
                    <li>
                        @Html.ActionLink("Gestão de Produtos", "Index", "Produtos")
                    </li>
                </ul>
            </div>
        </div>
    </div>
    @*Tudo html, apenas aqui temos o MVC*@
    <div class="container body-content">
        @RenderBody()
        <hr />
        <br />
        <footer class="border-top footer text-muted" style="text-align: center;">
            <div class="container">
                <p style="color:black">&copy; @DateTime.Now.Year - Conceitos MVC - Gisele da Silva Cidral</p>
            </div>
                </footer>
    </div>

    <script src="~/Scripts/jquery-1.9.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>